// This document is included in every project that submodules it.

=== Drupalizer tasks

*Drupalizer* is a Fabric script on top of Docker and tightly integrated with Drush and Drupal that provides the developer high-level tasks to manage the local development environment.

TIP: Drupalizer is configured as a git submodule of the SFL Boilerplate project.


For a complete overview of all available commands, run:

 $ fab --list

==== Top-level tasks

The top-levels tasks are larger tasks that include others. They are the most commonly called tasks.

* _Setup_ the Docker container, and _run_ a full Drupal installation:

 $ fab local_setup
 $ fab ls

* _Configure_ and _run_ the Behat tests:

 $ fab tests

TIP: The formatters used are _pretty_ and _junit_.

* _Build_ the Drupal platform:

 $ fab make

* _Run_ the Drupal installation

 $ fab install


==== Other common tasks

Some more atomic tasks supported by *Drupalizer* would be:

* _Start/stop_ the Docker container:

 $ fab crun
 $ fab cstop

* _Run_ the Behat tests (without configure):

 $ fab run_behat
 $ fab rb

* _Update_ the full codebase by running the top-level Makefile:

 $ fab site_update
 $ fab su

CAUTION: This command will wipe all the modifications made in the working directories.

* _Update_ the full codebase by running the top-level Makefile, _flush_ the database and _run_ the Drupal installation process:

 $ fab site_reinstall
 $ fab sr

CAUTION: This command will wipe all the modifications made in the working directories.

* _Bash_ into the Docker container:

 $ fab connect
