// This document is included in every project that submodules it.

=== Drupalizer tasks

*Drupalizer* is a Fabric script on top of Docker and tightly integrated with Drush and Drupal that provides the developer high-level tasks to manage the local development environment.

TIP: Drupalizer is configured as a git submodule for every project that needs to use it.

For a complete overview of all available commands, run:

 $ fab --list

To get a more nested or tree-like view, pass the following option:

 $ fab --list-format=nested --list

==== Top-level tasks

The top-levels tasks are larger tasks that include others. They are the most commonly called tasks.

* _Setup_ the Docker container, and _run_ a full Drupal installation:

 $ fab init

* _Run_ the Drupal installation

 $ fab install

 * _Update_ the Drupal installation

  $ fab update

 * _Configure_ and _run_ the Behat tests:

 $ fab test

TIP: The formatters used are _pretty_ and _junit_.


==== Other common tasks

Some more atomic tasks supported by *Drupalizer* would be:

* _Start/stop_ the Docker container:

 $ fab docker.container_start
 $ fab docker.container_stop

 * _Bash_ into the Docker container:

  $ fab docker.connect

* _Run_ the Behat tests (without configure):

 $ fab behat.run

* _Update_ the full codebase by running the top-level Makefile:

 $ fab drush.make

CAUTION: This command will wipe all the modifications made in the working directories.

* _Archive_ the full codebase and the database using drush archive_dump:

 $ fab drush.archive_dump
